const summer = require('os')

console.log(summer.type())
console.log(summer.version())
console.log(summer.cpus())
console.log(summer.freemem())
console.log(summer.hostname())
console.log(summer.arch())
console.log(summer.userInfo())
console.log(summer.homedir())
console.log(summer.loadavg())
console.log(summer.totalmem())
console.log(summer.machine())
console.log(summer.release())
console.log(__dirname)
console.log(__filename)